export {
  defineDelegation,
  defineOperation,
  defineOperationDescriptor,
  defineOperationMetadata,
  definePrincipal,
  defineTrellis,
  executeOperationRef,
  getOperationMetadata,
  implementOperation,
  previewOf,
  previewOperationRef,
  projectOperationRef,
  transportExecuteOperationRef,
  trellisBackendLaneMetadataKey,
  trellisOperationMetadataKey,
  trellisOperationProjectionMetadataKey,
  unsafe,
} from '../functions/index.js'

export {
  canonicalizeForwardingArgs,
  createTrustedForwardingEnvelope,
  hashForwardingArgs,
  TrustedForwardingEnvelopeError,
  verifyTrustedForwardingEnvelope,
} from '../trusted-forwarding/envelope.js'
export {
  clearTrustedForwardingContext,
  createTrustedForwardingEnvelopeArgs,
  extractSubject,
  getForwardedDelegation,
  getForwardedPrincipal,
  getTrustedForwardingKeyProductionIssue,
  setTrustedForwardingContext,
  withTrustedForwarding,
} from '../trusted-forwarding/index.js'

export type {
  ActorAccessor,
  DefaultPrincipal,
  Delegation,
  DelegationAccessor,
  DelegationDefinition,
  DestructiveOperationPreview,
  FunctionsCtxExtension,
  InferOperationLoaded,
  InferOperationPreview,
  InferOperationResult,
  McpWriteSafety,
  OperationDefinition,
  OperationDescriptor,
  OperationIdOf,
  OperationKind,
  OperationMetadataDefinition,
  OperationExecutionsById,
  OperationProjectionRef,
  OperationPreviewsById,
  OperationsById,
  PrincipalAccessor,
  PrincipalDefinition,
  RegisteredOperationDefinition,
  RegisteredOperationExecution,
  RegisteredOperationId,
  RegisteredOperationPreview,
  RegisteredOperationProjections,
  RegisteredOperations,
  StructuredGuard,
  StructuredHandlerDefinition,
  StructuredLoadedValue,
  TrellisOperationMetadata,
  TrellisOperationProjectionMetadata,
  TrellisBackendLane,
  TrellisUnsafePermit,
  ValidateOperationDefinition,
  ValidateOperationId,
  ValidateOperationProjection,
  ValidateOperationProjectionRef,
  ValidateRegisteredOperationId,
} from '../functions/index.js'

export type {
  CreateTrustedForwardingEnvelopeOptions,
  TrustedForwardingEnvelopePayload,
  TrustedForwardingPurpose,
  TrustedForwardingTransport,
  VerifyTrustedForwardingEnvelopeOptions,
} from '../trusted-forwarding/envelope.js'
