packages:
  - 'apps/*'
  - 'examples/*'
  - 'labs/*'
  - 'packages/*'
  - 'tests/fixtures/doctor-*'

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - isolated-vm
  - unrs-resolver
  - vue-demi
