import { createClient, type AuthFunctions, type GenericCtx } from '@convex-dev/better-auth'
import { convex } from '@convex-dev/better-auth/plugins'
import { betterAuth } from 'better-auth'
import type { BetterAuthUserDocLike } from 'better-convex-nuxt/server/createUserSyncTriggers'
import { ConvexError, v } from 'convex/values'

import { components, internal } from './_generated/api'
import type { DataModel, Id } from './_generated/dataModel'
import { internalMutation, type MutationCtx } from './_generated/server'
import authConfig from './auth.config'

type AgencyUserDoc = {
  _id: Id<'users'>
  subject: string
  name?: string
  email?: string
  createdAt: number
  updatedAt: number
}

type BetterAuthUserPage = {
  page: BetterAuthUserDocLike[]
  continueCursor: string
  isDone: boolean
}

const authFunctions: AuthFunctions = internal.auth

function isIpv4Loopback(hostname: string): boolean {
  const match = /^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/.exec(hostname)
  if (!match) return false
  const octets = match.slice(1).map(Number)
  return octets.every((octet) => octet <= 255) && octets[0] === 127
}

function isLoopbackHost(hostname: string): boolean {
  const host = hostname.toLowerCase()
  return (
    host === 'localhost' ||
    host.endsWith('.localhost') ||
    host === '[::1]' ||
    host === '::1' ||
    isIpv4Loopback(host)
  )
}

function requireStrongAuthSecret(): string {
  const secret = process.env.BETTER_AUTH_SECRET
  if (!secret) throw new Error('BETTER_AUTH_SECRET is required')
  if (secret.trim() !== secret || secret.length < 32) {
    throw new Error(
      'BETTER_AUTH_SECRET must be at least 32 characters and generated by a secure random source',
    )
  }
  return secret
}

function requireAuthEnvironment(): { siteUrl: string; secret: string } {
  const siteUrl = process.env.SITE_URL
  if (!siteUrl) throw new Error('SITE_URL is required')
  const secret = requireStrongAuthSecret()

  const parsed = new URL(siteUrl)
  if (parsed.origin !== siteUrl) {
    throw new Error('SITE_URL must be an exact origin without a path, query, or fragment')
  }

  const isLocalSite = isLoopbackHost(parsed.hostname)
  if (parsed.protocol !== 'https:' && !(parsed.protocol === 'http:' && isLocalSite)) {
    throw new Error('SITE_URL must use HTTPS except for loopback HTTP')
  }

  return { siteUrl, secret }
}

const duplicateActorMessage =
  'Duplicate Agency user actors require explicit reference reconciliation'

function userProjectionPatch(user: BetterAuthUserDocLike, existing: AgencyUserDoc, now: number) {
  const name = user.name ?? undefined
  const email = user.email ?? undefined
  if (name === existing.name && email === existing.email) return null

  return { name, email, updatedAt: now }
}

async function syncAgencyUserActor(
  ctx: MutationCtx,
  user: BetterAuthUserDocLike,
  insertIfMissing: boolean,
): Promise<'inserted' | 'patched' | 'skipped'> {
  const actors = await ctx.db
    .query('users')
    .withIndex('by_subject', (q) => q.eq('subject', user._id))
    .take(2)
  if (actors.length > 1) {
    // These rows are stable domain actors referenced throughout the Agency
    // schema, not disposable projections. Choosing and deleting one here could
    // leave organizations, memberships, projects, or audit events dangling.
    throw new ConvexError(duplicateActorMessage)
  }

  const actor = actors[0]
  const now = Date.now()
  if (!actor) {
    if (!insertIfMissing) return 'skipped'

    await ctx.db.insert('users', {
      subject: user._id,
      name: user.name ?? undefined,
      email: user.email ?? undefined,
      createdAt: now,
      updatedAt: now,
    })
    return 'inserted'
  }

  const patch = userProjectionPatch(user, actor, now)
  if (!patch) return 'skipped'

  await ctx.db.patch(actor._id, patch)
  return 'patched'
}

export const authComponent = createClient<DataModel>(components.betterAuth, {
  authFunctions,
  triggers: {
    user: {
      onCreate: async (ctx, user) => {
        await syncAgencyUserActor(ctx, user, true)
      },
      onUpdate: async (ctx, user) => {
        await syncAgencyUserActor(ctx, user, false)
      },
      onDelete: async (ctx, user) => {
        // Keep the stable actor and its references, but remove the display PII
        // copied from the deleted Better Auth user.
        await syncAgencyUserActor(ctx, { _id: user._id }, false)
      },
    },
  },
})

export const { onCreate, onUpdate, onDelete } = authComponent.triggersApi()

/** Rebuild one bounded page of the app user projection from Better Auth user truth. */
export const rebuildUserProjectionBatch = internalMutation({
  args: { cursor: v.union(v.string(), v.null()) },
  handler: async (ctx, args) => {
    const users = (await ctx.runQuery(components.betterAuth.adapter.findMany, {
      model: 'user',
      paginationOpts: { cursor: args.cursor, numItems: 100 },
    })) as BetterAuthUserPage
    const result = { inserted: 0, patched: 0, skipped: 0 }
    for (const user of users.page) {
      const outcome = await syncAgencyUserActor(ctx, user, true)
      result[outcome] += 1
    }

    return {
      ...result,
      continueCursor: users.continueCursor,
      isDone: users.isDone,
    }
  },
})

export function createAuth(ctx: GenericCtx<DataModel>) {
  const { siteUrl, secret } = requireAuthEnvironment()

  return betterAuth({
    baseURL: siteUrl,
    secret,
    database: authComponent.adapter(ctx),
    emailAndPassword: {
      enabled: true,
      minPasswordLength: 15,
      autoSignIn: false,
    },
    plugins: [convex({ authConfig })],
    trustedOrigins: [siteUrl],
  })
}
