import { createClient, type AuthFunctions, type GenericCtx } from '@convex-dev/better-auth'
import { convex } from '@convex-dev/better-auth/plugins'
import { betterAuth, type BetterAuthOptions } from 'better-auth'
import { createAccessControl, organization } from 'better-auth/plugins'
import {
  createUserSyncTriggers,
  type BetterAuthUserDocLike,
} from 'better-convex-nuxt/server/createUserSyncTriggers'
import { v } from 'convex/values'

import type { OrganizationRole } from '../shared/organizationRoles'
import { components, internal } from './_generated/api'
import type { DataModel, Doc } from './_generated/dataModel'
import { internalMutation } from './_generated/server'
import authConfig from './auth.config'
import authSchema from './betterAuth/schema'
import { escapeEmailHtml, sendStarterEmail } from './lib/authEmail'

const authFunctions: AuthFunctions = internal.auth

function isIpv4Loopback(hostname: string): boolean {
  const match = /^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/.exec(hostname)
  if (!match) return false
  const octets = match.slice(1).map(Number)
  return octets.every((octet) => octet <= 255) && octets[0] === 127
}

function isLocalSiteOrigin(siteUrl: string): boolean {
  const host = new URL(siteUrl).hostname.toLowerCase()
  return (
    host === 'localhost' ||
    host.endsWith('.localhost') ||
    host === '[::1]' ||
    host === '::1' ||
    isIpv4Loopback(host)
  )
}

function assertExactSiteOrigin(siteUrl: string): void {
  const parsed = new URL(siteUrl)
  if (parsed.origin !== siteUrl) {
    throw new Error('SITE_URL must be an exact origin without a path, query, or fragment')
  }
  if (
    parsed.protocol !== 'https:' &&
    !(parsed.protocol === 'http:' && isLocalSiteOrigin(siteUrl))
  ) {
    throw new Error('SITE_URL must use HTTPS except for loopback HTTP')
  }
}

function requireStrongAuthSecret(): string {
  const secret = process.env.BETTER_AUTH_SECRET
  if (!secret) throw new Error('BETTER_AUTH_SECRET is required')
  if (secret.trim() !== secret || secret.length < 32) {
    throw new Error(
      'BETTER_AUTH_SECRET must be at least 32 characters and generated by a secure random source',
    )
  }
  return secret
}

type InvitationEmailData = {
  id: string
  email: string
  organization: {
    name: string
  }
  inviter: {
    user: {
      name?: string | null
      email: string
    }
  }
}

type VerificationEmailData = {
  url: string
  user: {
    email: string
  }
}

type BetterAuthUserPage = {
  page: BetterAuthUserDocLike[]
  continueCursor: string
  isDone: boolean
}

const accessControl = createAccessControl({
  organization: ['update'],
  member: ['create', 'update', 'delete'],
  invitation: ['create', 'cancel'],
  team: ['create', 'update'],
  project: ['create', 'read', 'update', 'delete'],
})

const ownerRole = accessControl.newRole({
  organization: ['update'],
  member: ['create', 'update', 'delete'],
  invitation: ['create', 'cancel'],
  team: ['create', 'update'],
  project: ['create', 'read', 'update', 'delete'],
})

const adminRole = accessControl.newRole({
  organization: ['update'],
  member: ['create', 'update', 'delete'],
  invitation: ['create', 'cancel'],
  team: ['create', 'update'],
  project: ['create', 'read', 'update', 'delete'],
})

const memberRole = accessControl.newRole({
  organization: [],
  member: [],
  invitation: [],
  team: [],
  project: ['create', 'read', 'update'],
})

const viewerRole = accessControl.newRole({
  organization: [],
  member: [],
  invitation: [],
  team: [],
  project: ['read'],
})

const organizationRoleConfig = {
  owner: ownerRole,
  admin: adminRole,
  member: memberRole,
  viewer: viewerRole,
} satisfies Record<
  OrganizationRole,
  typeof ownerRole | typeof adminRole | typeof memberRole | typeof viewerRole
>

function invitationLink(siteUrl: string, invitationId: string) {
  return `${siteUrl.replace(/\/+$/, '')}/invitations/${encodeURIComponent(invitationId)}`
}

async function sendInvitationEmail(siteUrl: string, data: InvitationEmailData) {
  const link = invitationLink(siteUrl, data.id)
  const inviterName = data.inviter.user.name?.trim() || data.inviter.user.email
  const escapedInviterName = escapeEmailHtml(inviterName)
  const escapedOrganizationName = escapeEmailHtml(data.organization.name)
  const escapedLink = escapeEmailHtml(link)
  await sendStarterEmail({
    recipient: data.email,
    siteUrl,
    fallbackLabel: 'Invitation link',
    fallbackUrl: link,
    content: {
      subject: `${inviterName} invited you to join ${data.organization.name}`,
      text: [
        `${inviterName} invited you to join ${data.organization.name}.`,
        '',
        `Accept the invitation: ${link}`,
      ].join('\n'),
      html: `<p>${escapedInviterName} invited you to join <strong>${escapedOrganizationName}</strong>.</p><p><a href="${escapedLink}">Accept the invitation</a></p>`,
    },
  })
}

async function sendVerificationEmail(siteUrl: string, data: VerificationEmailData) {
  const escapedUrl = escapeEmailHtml(data.url)
  await sendStarterEmail({
    recipient: data.user.email,
    siteUrl,
    fallbackLabel: 'Verification link',
    fallbackUrl: data.url,
    content: {
      subject: 'Verify your email address',
      text: `Click the link to verify your email: ${data.url}`,
      html: `<p><a href="${escapedUrl}">Verify your email address</a></p>`,
    },
  })
}

function userProjectionFields(user: BetterAuthUserDocLike) {
  return {
    name: user.name ?? undefined,
    email: user.email ?? undefined,
    image: user.image ?? undefined,
  }
}

function userProjectionPatch(user: BetterAuthUserDocLike, existing: Doc<'users'>, now: number) {
  const fields = userProjectionFields(user)
  if (
    fields.name === existing.name &&
    fields.email === existing.email &&
    fields.image === existing.image
  ) {
    return null
  }

  return { ...fields, updatedAt: now }
}

const userProjection = createUserSyncTriggers<BetterAuthUserDocLike, Doc<'users'>>({
  table: 'users',
  index: 'by_auth_user_id',
  authIdField: 'authUserId',
  createDoc: ({ user, now }) => ({
    authUserId: user._id,
    ...userProjectionFields(user),
    createdAt: now,
    updatedAt: now,
  }),
  patchDoc: ({ user, existing, now }) => userProjectionPatch(user, existing, now),
  rebuildDoc: ({ user, existing, now }) => userProjectionPatch(user, existing, now),
})

export const authComponent = createClient<DataModel, typeof authSchema>(components.betterAuth, {
  local: {
    schema: authSchema,
  },
  authFunctions,
  triggers: {
    user: {
      onCreate: userProjection.user.onCreate,
      onUpdate: userProjection.user.onUpdate,
      onDelete: userProjection.user.onDelete,
    },
  },
})

export const createAuthOptions = (ctx: GenericCtx<DataModel>) => {
  const siteUrl = process.env.SITE_URL ?? 'http://localhost:3000'
  const authSecret = process.env.BETTER_AUTH_SECRET ?? 'schema-generation-secret'
  assertExactSiteOrigin(siteUrl)

  return {
    baseURL: siteUrl,
    secret: authSecret,
    database: authComponent.adapter(ctx),
    emailAndPassword: {
      enabled: true,
      minPasswordLength: 15,
      autoSignIn: false,
      requireEmailVerification: true,
    },
    emailVerification: {
      sendOnSignIn: true,
      sendOnSignUp: true,
      autoSignInAfterVerification: true,
      async sendVerificationEmail(data) {
        await sendVerificationEmail(siteUrl, data as VerificationEmailData)
      },
    },
    plugins: [
      organization({
        ac: accessControl,
        roles: organizationRoleConfig,
        requireEmailVerificationOnInvitation: true,
        async sendInvitationEmail(data) {
          await sendInvitationEmail(siteUrl, data as InvitationEmailData)
        },
        teams: {
          enabled: true,
        },
      }),
      convex({
        authConfig,
        jwt: {
          definePayload: ({ user }) => ({
            name: user.name,
            email: user.email,
            emailVerified: user.emailVerified,
            image: user.image ?? undefined,
          }),
        },
      }),
    ],
    session: {
      expiresIn: 60 * 60 * 24 * 7,
      updateAge: 60 * 60 * 24,
    },
    advanced: {
      database: {
        generateId: false,
      },
    },
    trustedOrigins: [siteUrl],
  } satisfies BetterAuthOptions
}

export const createAuth = (ctx: GenericCtx<DataModel>) => {
  const siteUrl = process.env.SITE_URL
  if (!siteUrl) {
    throw new Error('SITE_URL is required')
  }
  requireStrongAuthSecret()
  assertExactSiteOrigin(siteUrl)

  return betterAuth(createAuthOptions(ctx))
}

export type AppAuth = ReturnType<typeof createAuth>

export const { onCreate, onUpdate, onDelete } = authComponent.triggersApi()

/** Reconcile one bounded page of the display-only user projection. */
export const rebuildUserProjectionBatch = internalMutation({
  args: { cursor: v.union(v.string(), v.null()) },
  handler: async (ctx, args) => {
    const users = (await ctx.runQuery(components.betterAuth.adapter.findMany, {
      model: 'user',
      paginationOpts: { cursor: args.cursor, numItems: 100 },
    })) as BetterAuthUserPage
    const result = await userProjection.user.rebuild(ctx, users.page)

    return {
      ...result,
      continueCursor: users.continueCursor,
      isDone: users.isDone,
    }
  },
})
