/** This file is generated by Better Convex Nuxt. Do not edit. */
import { defineSchema, defineTable } from 'convex/server'
import { v } from 'convex/values'

export const tables = {
  user: defineTable({
    id: v.string(),
    name: v.string(),
    email: v.string(),
    emailVerified: v.boolean(),
    image: v.union(v.null(), v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index('id', ['id'])
    .index('name', ['name'])
    .index('email', ['email'])
    .index('createdAt', ['createdAt']),
  session: defineTable({
    id: v.string(),
    expiresAt: v.number(),
    token: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
    ipAddress: v.union(v.null(), v.string()),
    userAgent: v.union(v.null(), v.string()),
    userId: v.string(),
    activeOrganizationId: v.union(v.null(), v.string()),
  })
    .index('id', ['id'])
    .index('expiresAt', ['expiresAt'])
    .index('userId_expiresAt', ['userId', 'expiresAt'])
    .index('token', ['token'])
    .index('createdAt', ['createdAt'])
    .index('userId', ['userId']),
  account: defineTable({
    id: v.string(),
    accountId: v.string(),
    providerId: v.string(),
    userId: v.string(),
    accessToken: v.union(v.null(), v.string()),
    refreshToken: v.union(v.null(), v.string()),
    idToken: v.union(v.null(), v.string()),
    accessTokenExpiresAt: v.union(v.null(), v.number()),
    refreshTokenExpiresAt: v.union(v.null(), v.number()),
    scope: v.union(v.null(), v.string()),
    password: v.union(v.null(), v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index('id', ['id'])
    .index('accountId', ['accountId'])
    .index('accountId_providerId', ['accountId', 'providerId'])
    .index('providerId_userId', ['providerId', 'userId'])
    .index('userId', ['userId'])
    .index('createdAt', ['createdAt']),
  verification: defineTable({
    id: v.string(),
    identifier: v.string(),
    value: v.string(),
    expiresAt: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index('id', ['id'])
    .index('expiresAt', ['expiresAt'])
    .index('identifier', ['identifier'])
    .index('identifier_createdAt', ['identifier', 'createdAt'])
    .index('createdAt', ['createdAt']),
  organization: defineTable({
    id: v.string(),
    name: v.string(),
    slug: v.string(),
    logo: v.union(v.null(), v.string()),
    createdAt: v.number(),
    metadata: v.union(v.null(), v.string()),
  })
    .index('id', ['id'])
    .index('name', ['name'])
    .index('slug', ['slug'])
    .index('createdAt', ['createdAt']),
  member: defineTable({
    id: v.string(),
    organizationId: v.string(),
    userId: v.string(),
    role: v.string(),
    createdAt: v.number(),
  })
    .index('id', ['id'])
    .index('organizationId_userId', ['organizationId', 'userId'])
    .index('organizationId', ['organizationId'])
    .index('userId', ['userId'])
    .index('role', ['role'])
    .index('createdAt', ['createdAt']),
  invitation: defineTable({
    id: v.string(),
    organizationId: v.string(),
    email: v.string(),
    role: v.union(v.null(), v.string()),
    status: v.string(),
    expiresAt: v.number(),
    createdAt: v.number(),
    inviterId: v.string(),
  })
    .index('id', ['id'])
    .index('email_organizationId_status', ['email', 'organizationId', 'status'])
    .index('organizationId_status_createdAt', ['organizationId', 'status', 'createdAt'])
    .index('organizationId', ['organizationId'])
    .index('email', ['email'])
    .index('role', ['role'])
    .index('status', ['status'])
    .index('createdAt', ['createdAt'])
    .index('inviterId', ['inviterId']),
  jwks: defineTable({
    id: v.string(),
    publicKey: v.string(),
    privateKey: v.string(),
    createdAt: v.number(),
    expiresAt: v.union(v.null(), v.number()),
    alg: v.union(v.null(), v.string()),
    crv: v.union(v.null(), v.string()),
  })
    .index('id', ['id'])
    .index('createdAt', ['createdAt']),
  rateLimit: defineTable({
    id: v.string(),
    key: v.string(),
    count: v.number(),
    lastRequest: v.number(),
  })
    .index('id', ['id'])
    .index('key', ['key']),
} as const

const schema = defineSchema(tables)
Object.defineProperty(schema, '__betterConvexNuxtAuthSchemaFingerprint', {
  value: 'bcn-auth-schema-v2:bc45d134f76b8286',
})

export default schema
