/** This file is generated by Better Convex Nuxt. Do not edit. */
import { defineSchema, defineTable } from 'convex/server'
import { v } from 'convex/values'

export const tables = {
  user: defineTable({
    id: v.string(),
    name: v.string(),
    email: v.string(),
    emailVerified: v.boolean(),
    image: v.union(v.null(), v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index('id', ['id'])
    .index('name', ['name'])
    .index('email', ['email'])
    .index('createdAt', ['createdAt']),
  session: defineTable({
    id: v.string(),
    expiresAt: v.number(),
    token: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
    ipAddress: v.union(v.null(), v.string()),
    userAgent: v.union(v.null(), v.string()),
    userId: v.string(),
  })
    .index('id', ['id'])
    .index('expiresAt', ['expiresAt'])
    .index('userId_expiresAt', ['userId', 'expiresAt'])
    .index('token', ['token'])
    .index('createdAt', ['createdAt'])
    .index('userId', ['userId']),
  account: defineTable({
    id: v.string(),
    accountId: v.string(),
    providerId: v.string(),
    userId: v.string(),
    accessToken: v.union(v.null(), v.string()),
    refreshToken: v.union(v.null(), v.string()),
    idToken: v.union(v.null(), v.string()),
    accessTokenExpiresAt: v.union(v.null(), v.number()),
    refreshTokenExpiresAt: v.union(v.null(), v.number()),
    scope: v.union(v.null(), v.string()),
    password: v.union(v.null(), v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index('id', ['id'])
    .index('accountId', ['accountId'])
    .index('accountId_providerId', ['accountId', 'providerId'])
    .index('providerId_userId', ['providerId', 'userId'])
    .index('userId', ['userId'])
    .index('createdAt', ['createdAt']),
  verification: defineTable({
    id: v.string(),
    identifier: v.string(),
    value: v.string(),
    expiresAt: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index('id', ['id'])
    .index('expiresAt', ['expiresAt'])
    .index('identifier', ['identifier'])
    .index('identifier_createdAt', ['identifier', 'createdAt'])
    .index('createdAt', ['createdAt']),
  jwks: defineTable({
    id: v.string(),
    publicKey: v.string(),
    privateKey: v.string(),
    createdAt: v.number(),
    expiresAt: v.union(v.null(), v.number()),
    alg: v.union(v.null(), v.string()),
    crv: v.union(v.null(), v.string()),
  })
    .index('id', ['id'])
    .index('createdAt', ['createdAt']),
  oauthClient: defineTable({
    id: v.string(),
    clientId: v.string(),
    clientSecret: v.union(v.null(), v.string()),
    disabled: v.union(v.null(), v.boolean()),
    skipConsent: v.union(v.null(), v.boolean()),
    enableEndSession: v.union(v.null(), v.boolean()),
    subjectType: v.union(v.null(), v.string()),
    scopes: v.union(v.null(), v.array(v.string())),
    userId: v.union(v.null(), v.string()),
    createdAt: v.union(v.null(), v.number()),
    updatedAt: v.union(v.null(), v.number()),
    name: v.union(v.null(), v.string()),
    uri: v.union(v.null(), v.string()),
    icon: v.union(v.null(), v.string()),
    contacts: v.union(v.null(), v.array(v.string())),
    tos: v.union(v.null(), v.string()),
    policy: v.union(v.null(), v.string()),
    softwareId: v.union(v.null(), v.string()),
    softwareVersion: v.union(v.null(), v.string()),
    softwareStatement: v.union(v.null(), v.string()),
    redirectUris: v.array(v.string()),
    postLogoutRedirectUris: v.union(v.null(), v.array(v.string())),
    backchannelLogoutUri: v.union(v.null(), v.string()),
    backchannelLogoutSessionRequired: v.union(v.null(), v.boolean()),
    tokenEndpointAuthMethod: v.union(v.null(), v.string()),
    jwks: v.union(v.null(), v.string()),
    jwksUri: v.union(v.null(), v.string()),
    grantTypes: v.union(v.null(), v.array(v.string())),
    responseTypes: v.union(v.null(), v.array(v.string())),
    public: v.union(v.null(), v.boolean()),
    type: v.union(v.null(), v.string()),
    requirePKCE: v.union(v.null(), v.boolean()),
    dpopBoundAccessTokens: v.union(v.null(), v.boolean()),
    referenceId: v.union(v.null(), v.string()),
    metadata: v.union(v.null(), v.string()),
  })
    .index('id', ['id'])
    .index('clientId', ['clientId'])
    .index('userId', ['userId'])
    .index('createdAt', ['createdAt']),
  oauthResource: defineTable({
    id: v.string(),
    identifier: v.string(),
    name: v.string(),
    accessTokenTtl: v.union(v.null(), v.number()),
    refreshTokenTtl: v.union(v.null(), v.number()),
    signingAlgorithm: v.union(v.null(), v.string()),
    signingKeyId: v.union(v.null(), v.string()),
    allowedScopes: v.union(v.null(), v.array(v.string())),
    customClaims: v.union(v.null(), v.string()),
    dpopBoundAccessTokensRequired: v.union(v.null(), v.boolean()),
    disabled: v.union(v.null(), v.boolean()),
    createdAt: v.union(v.null(), v.number()),
    updatedAt: v.union(v.null(), v.number()),
    policyVersion: v.union(v.null(), v.number()),
    metadata: v.union(v.null(), v.string()),
  })
    .index('id', ['id'])
    .index('identifier', ['identifier'])
    .index('createdAt', ['createdAt']),
  oauthClientResource: defineTable({
    id: v.string(),
    clientId: v.string(),
    resourceId: v.string(),
    metadata: v.union(v.null(), v.string()),
    createdAt: v.union(v.null(), v.number()),
  })
    .index('id', ['id'])
    .index('clientId', ['clientId'])
    .index('resourceId', ['resourceId'])
    .index('createdAt', ['createdAt']),
  oauthRefreshToken: defineTable({
    id: v.string(),
    token: v.string(),
    clientId: v.string(),
    sessionId: v.union(v.null(), v.string()),
    userId: v.string(),
    referenceId: v.union(v.null(), v.string()),
    authorizationCodeId: v.union(v.null(), v.string()),
    resources: v.union(v.null(), v.array(v.string())),
    requestedUserInfoClaims: v.union(v.null(), v.array(v.string())),
    expiresAt: v.union(v.null(), v.number()),
    createdAt: v.union(v.null(), v.number()),
    revoked: v.union(v.null(), v.number()),
    rotatedAt: v.union(v.null(), v.number()),
    rotationReplayResponse: v.union(v.null(), v.string()),
    rotationReplayExpiresAt: v.union(v.null(), v.number()),
    authTime: v.union(v.null(), v.number()),
    confirmation: v.union(v.null(), v.string()),
    scopes: v.array(v.string()),
  })
    .index('id', ['id'])
    .index('token', ['token'])
    .index('clientId', ['clientId'])
    .index('sessionId', ['sessionId'])
    .index('userId', ['userId'])
    .index('authorizationCodeId', ['authorizationCodeId'])
    .index('createdAt', ['createdAt']),
  oauthAccessToken: defineTable({
    id: v.string(),
    token: v.union(v.null(), v.string()),
    clientId: v.string(),
    sessionId: v.union(v.null(), v.string()),
    userId: v.union(v.null(), v.string()),
    referenceId: v.union(v.null(), v.string()),
    authorizationCodeId: v.union(v.null(), v.string()),
    resources: v.union(v.null(), v.array(v.string())),
    requestedUserInfoClaims: v.union(v.null(), v.array(v.string())),
    refreshId: v.union(v.null(), v.string()),
    expiresAt: v.union(v.null(), v.number()),
    createdAt: v.union(v.null(), v.number()),
    revoked: v.union(v.null(), v.number()),
    confirmation: v.union(v.null(), v.string()),
    scopes: v.array(v.string()),
  })
    .index('id', ['id'])
    .index('token', ['token'])
    .index('clientId', ['clientId'])
    .index('sessionId', ['sessionId'])
    .index('userId', ['userId'])
    .index('authorizationCodeId', ['authorizationCodeId'])
    .index('refreshId', ['refreshId'])
    .index('createdAt', ['createdAt']),
  oauthConsent: defineTable({
    id: v.string(),
    clientId: v.string(),
    userId: v.union(v.null(), v.string()),
    referenceId: v.union(v.null(), v.string()),
    resources: v.union(v.null(), v.array(v.string())),
    requestedUserInfoClaims: v.union(v.null(), v.array(v.string())),
    scopes: v.array(v.string()),
    createdAt: v.union(v.null(), v.number()),
    updatedAt: v.union(v.null(), v.number()),
  })
    .index('id', ['id'])
    .index('clientId_userId', ['clientId', 'userId'])
    .index('clientId', ['clientId'])
    .index('userId', ['userId'])
    .index('createdAt', ['createdAt']),
  oauthClientAssertion: defineTable({
    id: v.string(),
    expiresAt: v.number(),
  }).index('id', ['id']),
  rateLimit: defineTable({
    id: v.string(),
    key: v.string(),
    count: v.number(),
    lastRequest: v.number(),
  })
    .index('id', ['id'])
    .index('key', ['key']),
} as const

const schema = defineSchema(tables)
Object.defineProperty(schema, '__betterConvexNuxtAuthSchemaFingerprint', {
  value: 'bcn-auth-schema-v2:1c24666cccfcb1cb',
})

export default schema
