import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import { describe, expect, it } from 'vitest'

const repoRoot = join(import.meta.dirname, '../..')
const authApps = [
  'demo',
  'playground',
  'starters/agency',
  'starters/agentic-saas',
  'starters/mcp-agent',
  'starters/team',
] as const
const passwordApps = authApps.filter((app) => app !== 'demo')
const passwordForms = [
  'playground/pages/auth/signup.vue',
  'starters/agency/app/pages/agency.vue',
  'starters/agentic-saas/app/pages/index.vue',
  'starters/mcp-agent/app/components/demo/AuthSection.vue',
  'starters/team/app/components/AuthPanel.vue',
] as const
const passwordRecipeDocs = ['docs/content/docs/1.guide/3.auth.md'] as const
const genericSignInForms = [
  'playground/pages/auth/signin.vue',
  'starters/team/app/components/AuthPanel.vue',
  'starters/mcp-agent/app/composables/useMcpDemoAuth.ts',
  'starters/agentic-saas/app/pages/index.vue',
] as const

function read(path: string): string {
  return readFileSync(join(repoRoot, path), 'utf8')
}

describe('shipped Better Auth factory invariants', () => {
  it.each(authApps)('%s fails closed on runtime secret and unsafe application origins', (app) => {
    const auth = read(`${app}/convex/auth.ts`)

    expect(auth).toContain("throw new Error('SITE_URL is required')")
    expect(auth).toContain("throw new Error('BETTER_AUTH_SECRET is required')")
    expect(auth).toContain('secret.trim() !== secret')
    expect(auth).toContain('secret.length < 32')
    expect(auth).not.toContain('estimatedEntropy')
    expect(auth).toContain('generated by a secure random source')
    expect(auth).toContain('SITE_URL must be an exact origin')
    expect(auth).toContain('SITE_URL must use HTTPS except for loopback HTTP')
    expect(auth).toContain("host.endsWith('.localhost')")
    expect(auth).toContain("host === '[::1]'")
    expect(auth).toContain('isIpv4Loopback(host)')
    expect(auth).toContain('trustedOrigins: [siteUrl]')
    expect(auth).not.toContain('trustedOrigins: isLocalSite')
    expect(auth).not.toContain('localTrustedOrigins')
  })

  it.each(authApps)('%s registers only the lazy Better Auth HTTP ceremony', (app) => {
    const http = read(`${app}/convex/http.ts`)

    expect(http).toContain('authComponent.registerRoutesLazy(http, createAuth)')
    expect(http).not.toMatch(/authComponent\.registerRoutes\(/)
  })

  it.each(passwordApps)('%s enforces the supported 15-character password floor', (app) => {
    const auth = read(`${app}/convex/auth.ts`)
    expect(auth).toContain('minPasswordLength: 15')
    expect(auth).toContain('autoSignIn: false')
  })

  it.each(passwordForms)('%s matches the backend password floor', (form) => {
    expect(read(form)).toContain('minlength="15"')
    expect(read(form)).not.toContain('minlength="8"')
  })

  it('does not prefill reusable passwords in maintained starter UI', () => {
    const agentic = read('starters/agentic-saas/app/pages/index.vue')
    const mcp = read('starters/mcp-agent/app/composables/useMcpDemoAuth.ts')

    expect(agentic).toContain("const ownerPassword = ref('')")
    expect(mcp).toContain("const password = ref('')")
    expect(agentic).not.toContain("const ownerPassword = ref('Password")
    expect(mcp).not.toContain("const password = ref('Password")
  })

  it.each(passwordRecipeDocs)('%s keeps copyable password factories hardened', (path) => {
    const source = read(path)
    const factoryCount = source.match(/emailAndPassword:\s*\{/g)?.length ?? 0

    expect(factoryCount).toBeGreaterThan(0)
    expect(source.match(/minPasswordLength:\s*15/g)).toHaveLength(factoryCount)
    expect(source.match(/autoSignIn:\s*false/g)).toHaveLength(factoryCount)
    expect(source.match(/authSecret\.length < 32/g)).toHaveLength(factoryCount)
    expect(source).not.toContain('estimatedEntropy')
    expect(source.match(/generated by a secure random source/g)).toHaveLength(factoryCount)
  })

  it('keeps canonical signup recipes on the explicit sign-in ceremony', () => {
    const guide = read('docs/content/docs/1.guide/3.auth.md')
    const securityGuide = read('docs/content/docs/4.auth-security/1.authentication.md')

    expect(guide.match(/router\.push\('\/signin'\)/g)).toHaveLength(2)
    expect(guide).not.toContain('// signIn/signUp synchronize Convex auth automatically')
    expect(securityGuide).toContain("navigateTo('/signin')")
  })

  it('does not expose Better Auth account-state errors in maintained sign-in UI', () => {
    const genericMessage =
      'Sign in could not be completed. Check your credentials and verify your email if required.'
    const guide = read('docs/content/docs/1.guide/3.auth.md')
    const securityGuide = read('docs/content/docs/4.auth-security/1.authentication.md')

    for (const path of genericSignInForms) {
      expect(read(path)).toContain(genericMessage)
    }
    expect(
      guide.match(new RegExp(genericMessage.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g')),
    ).toHaveLength(2)
    expect(guide).not.toContain('error.value = authError.message')
    expect(securityGuide.match(/Sign in could not be completed/g)).toHaveLength(3)
    expect(securityGuide).not.toContain('error.value = authError.message')
    expect(securityGuide).not.toContain("console.error('Sign in failed:', error.message)")
    expect(read('playground/pages/auth/signin.vue')).not.toContain('result.error.message')
    expect(read('starters/team/app/components/AuthPanel.vue')).not.toContain('result.error.message')
    expect(read('starters/mcp-agent/app/composables/useMcpDemoAuth.ts')).not.toContain(
      'result.error.message',
    )
    expect(read('starters/agentic-saas/app/pages/index.vue')).not.toContain(
      "new Error(error.message || 'Sign in failed')",
    )
  })

  it('documents password blocklist and distributed abuse-control ownership', () => {
    const security = read('SECURITY.md')

    expect(security).toContain('breached/common-password blocklist')
    expect(security).toContain('process-local defense in depth')
    expect(security).toContain('trusted-ingress per-account and per-IP limiter')
  })

  it('keeps route components on the app-lifetime session observer', () => {
    const guide = read('docs/content/docs/1.guide/3.auth.md')
    const securityGuide = read('docs/content/docs/4.auth-security/1.authentication.md')

    expect(guide).toContain('do not mount `client.useSession()` in route components')
    expect(securityGuide).toContain('Do not mount `client.useSession()` in route components')
    expect(guide).not.toContain('typed `client.useSession()` fields')
  })

  it('keeps the SaaS research page from becoming a second auth-factory source', () => {
    const architecture = read('docs/content/docs/8.architecture/1.saas-kit-direction.md')

    expect(architecture).toContain('Do not copy a second auth factory')
    expect(architecture).not.toContain('export function createAuthOptions')
  })

  it('keeps schema-changing plugin docs on the maintained factory source', () => {
    const securityGuide = read('docs/content/docs/4.auth-security/1.authentication.md')

    expect(securityGuide).toContain('This guide deliberately does not repeat that factory')
    expect(securityGuide).not.toContain('export function createAuthOptions')
    expect(securityGuide).not.toContain('createAuth({} as never)')
  })

  it('does not trust wildcard origins in the runnable playground', () => {
    const auth = read('playground/convex/auth.ts')

    expect(auth).toContain('trustedOrigins: [siteUrl]')
    expect(auth).not.toContain('http://localhost:*')
    expect(auth).not.toContain('http://127.0.0.1:*')
  })

  it('keeps schema-only placeholders out of the MCP request factory', () => {
    const auth = read('starters/mcp-agent/convex/auth.ts')

    expect(auth).not.toContain('localSecret')
    expect(auth).not.toContain('createAuthOptions')
    expect(auth).not.toMatch(/BETTER_AUTH_SECRET\s*\?\?/)
  })

  it('pins the conservative demo OAuth storage and account-linking policy', () => {
    const auth = read('demo/convex/auth.ts')

    expect(auth).toContain("throw new Error('GITHUB_CLIENT_ID is required')")
    expect(auth).toContain("throw new Error('GITHUB_CLIENT_SECRET is required')")
    expect(auth).toContain('encryptOAuthTokens: true')
    expect(auth).toContain('disableImplicitLinking: true')
    expect(auth).toContain('trustedProviders: []')
    expect(auth).toContain('allowDifferentEmails: false')
    expect(auth).toContain('allowUnlinkingAll: false')
  })

  it('keeps the agency identity-to-domain-user path rebuildable and usable', () => {
    const auth = read('starters/agency/convex/auth.ts')
    const page = read('starters/agency/app/pages/agency.vue')

    // Agency users are stable domain actors referenced by tenant and audit
    // records, not disposable display projections. Assert the required
    // lifecycle behavior without coupling this guard to the generic helper.
    expect(auth).toContain('syncAgencyUserActor(ctx, user, true)')
    expect(auth).toContain('syncAgencyUserActor(ctx, user, false)')
    expect(auth).toContain('syncAgencyUserActor(ctx, { _id: user._id }, false)')
    expect(auth).toContain('rebuildUserProjectionBatch = internalMutation')
    expect(page).toContain('useConvexAuth()')
    expect(page).toContain('await signUp.email')
    expect(page).toContain('await signIn.email')
    expect(page).not.toContain('await refresh()')
  })

  it('escapes dynamic Team transactional-email HTML at the delivery boundary', () => {
    const auth = read('starters/team/convex/auth.ts')
    const delivery = read('starters/team/convex/lib/authEmail.ts')

    expect(auth).toContain('escapeEmailHtml(inviterName)')
    expect(auth).toContain('escapeEmailHtml(data.organization.name)')
    expect(auth).toContain('escapeEmailHtml(link)')
    expect(auth).toContain('escapeEmailHtml(data.url)')
    expect(delivery).toMatch(/value\.replace\(\s*\/\[&<>"'\]\/g/)
    expect(delivery).not.toContain("process.env.ALLOW_TEST_RESET === 'true'")
  })
})
