import { beforeAll, describe, expect, it } from 'vitest'

describe('auth entrypoint exports', () => {
  let authApi: typeof import('../../src/runtime/auth/index')
  let trustedForwardingApi: typeof import('../../src/runtime/trusted-forwarding/index')
  let visibilityApi: typeof import('../../src/runtime/visibility/index')

  beforeAll(async () => {
    authApi = await import('../../src/runtime/auth/index')
    trustedForwardingApi = await import('../../src/runtime/trusted-forwarding/index')
    visibilityApi = await import('../../src/runtime/visibility/index')
  })

  it('exports the canonical auth primitives', () => {
    expect(authApi).toHaveProperty('and')
    expect(authApi).toHaveProperty('or')
    expect(authApi).toHaveProperty('defineActor')
    expect(authApi).toHaveProperty('defineGuard')
    expect(authApi).toHaveProperty('authRequired')
    expect(authApi).toHaveProperty('isAuthRequiredGuard')
    expect(authApi).toHaveProperty('isGuard')
    expect(authApi).toHaveProperty('open')
    expect(authApi).toHaveProperty('enforce')
    expect(authApi).toHaveProperty('can')
    expect(authApi).toHaveProperty('deny')
    expect(authApi).toHaveProperty('getAuth')
    expect(authApi).toHaveProperty('requireAuth')
    expect(authApi).toHaveProperty('requireRecord')
    expect(authApi).toHaveProperty('ensureTenant')
    expect(authApi).toHaveProperty('loadTenantResource')
    expect(authApi).toHaveProperty('defineAuth')
    expect(authApi).toHaveProperty('definePermissionContext')
    expect(authApi).not.toHaveProperty('withCan')
    expect(authApi).not.toHaveProperty('definePermissions')
    expect(authApi).not.toHaveProperty('createDefaultGetActor')
    expect(authApi).not.toHaveProperty('defineActorExtension')
    expect(authApi).not.toHaveProperty('defineActorFromMembership')
    expect(authApi).not.toHaveProperty('createFunctions')

    expect(trustedForwardingApi).toHaveProperty('getTrustedForwarding')
    expect(trustedForwardingApi).toHaveProperty('verifyTrustedForwardingKey')
    expect(trustedForwardingApi).toHaveProperty('withTrustedForwarding')
    expect(trustedForwardingApi).toHaveProperty('setTrustedForwardingContext')
    expect(trustedForwardingApi).toHaveProperty('clearTrustedForwardingContext')
    expect(trustedForwardingApi).toHaveProperty('getForwardedDelegation')
    expect(visibilityApi).toHaveProperty('defineCapabilities')
    expect(visibilityApi).toHaveProperty('defineRedaction')
  })
})
